// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (http://www.specflow.org/).
//      SpecFlow Version:2.3.2.0
//      SpecFlow Generator Version:2.3.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace SpecFlowSessionTests.Features
{
    using TechTalk.SpecFlow;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "2.3.2.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [NUnit.Framework.TestFixtureAttribute()]
    [NUnit.Framework.DescriptionAttribute("AddStudentsWithTable")]
    [NUnit.Framework.CategoryAttribute("demo")]
    public partial class AddStudentsWithTableFeature
    {
        
        private TechTalk.SpecFlow.ITestRunner testRunner;
        
#line 1 "AddStudentsWithTable.feature"
#line hidden
        
        [NUnit.Framework.OneTimeSetUpAttribute()]
        public virtual void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "AddStudentsWithTable", "\tIn order to avoid silly mistakes\r\n\tAs a admin\r\n\tI want to be told the students a" +
                    "re added", ProgrammingLanguage.CSharp, new string[] {
                        "demo"});
            testRunner.OnFeatureStart(featureInfo);
        }
        
        [NUnit.Framework.OneTimeTearDownAttribute()]
        public virtual void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        [NUnit.Framework.SetUpAttribute()]
        public virtual void TestInitialize()
        {
        }
        
        [NUnit.Framework.TearDownAttribute()]
        public virtual void ScenarioTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public virtual void ScenarioSetup(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioStart(scenarioInfo);
        }
        
        public virtual void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add New Students With Table")]
        [NUnit.Framework.CategoryAttribute("demo")]
        public virtual void AddNewStudentsWithTable()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add New Students With Table", new string[] {
                        "demo"});
#line 8
this.ScenarioSetup(scenarioInfo);
#line 9
 testRunner.Given("I am at the Demo Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 10
 testRunner.And("I login as admin", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table1 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Class",
                        "RollNo",
                        "GenderType"});
            table1.AddRow(new string[] {
                        "Kam",
                        "V",
                        "189",
                        "Female"});
#line 11
 testRunner.When("I Add students", ((string)(null)), table1, "When ");
#line 14
 testRunner.Then("I should see the added students", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
        
        [NUnit.Framework.TestAttribute()]
        [NUnit.Framework.DescriptionAttribute("Add New Students With Table in Bulk")]
        [NUnit.Framework.CategoryAttribute("demo")]
        public virtual void AddNewStudentsWithTableInBulk()
        {
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("Add New Students With Table in Bulk", new string[] {
                        "demo"});
#line 17
this.ScenarioSetup(scenarioInfo);
#line 18
 testRunner.Given("I am at the Demo Page", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line 19
 testRunner.And("I login as admin", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "And ");
#line hidden
            TechTalk.SpecFlow.Table table2 = new TechTalk.SpecFlow.Table(new string[] {
                        "Name",
                        "Class",
                        "RollNo",
                        "GenderType"});
            table2.AddRow(new string[] {
                        "Kam",
                        "V",
                        "189",
                        "Female"});
            table2.AddRow(new string[] {
                        "Barsha",
                        "VI",
                        "190",
                        "Female"});
            table2.AddRow(new string[] {
                        "Ramya",
                        "VII",
                        "191",
                        "Female"});
            table2.AddRow(new string[] {
                        "Test",
                        "VIII",
                        "129",
                        "Male"});
#line 20
 testRunner.When("I Add students in Bulk", ((string)(null)), table2, "When ");
#line 26
 testRunner.Then("I should see the added students", ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            this.ScenarioCleanup();
        }
    }
}
#pragma warning restore
#endregion
